# Generated by Django 5.1.6 on 2025-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (₺)')),
                ('stok', models.IntegerField(verbose_name='Stok Miktarı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
        ),
    ]
